### ISSUE TITLE
need help with weights.h5 file

### ISSUE THREAD

**Issue by zqianyu** [arturbeg/reinforcement_learning_oe#1]
hello, I would love to study your project, can you help me with that "DDQN25ep_NN=6_NN_BinomialA=0.01Actions=21TimeConstr=11Opt=RMSpropREW=_weights.h5" file, I can't run the code without this file

**Comment by AndreasTheodoulou** [comment]
Please set LOAD_PRETRAINED_WEIGHTS = False. In this way you will not need to load the pre-trained model.
