### ISSUE TITLE
"(self.get_price() -  self.get_price())" is this a bug?

### ISSUE THREAD

**Issue by zqianyu** [arturbeg/reinforcement_learning_oe#2]
may I ask at line 194 def reward part, "remaining_inventory*(self.get_price() -  self.get_price()) - A*(action**2)",  woudn't it be always zero?
in the paper the reward formula is qk*(Pk+1 - Pk) - a(Xk^2)

**Comment by AndreasTheodoulou** [comment]
Yes, that feels like a bug. We have ended up using the PAndLReward == True though, which doesn’t use that line of code
